# https://taskfile.dev

version: "3"

tasks:
  install:
    cmds:
      - go install -ldflags '-s -w -X "github.com/pot-code/web-cli/cmd.AppVersion={{.VERSION}}"'
    vars:
      VERSION:
        sh: git describe --tags